server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5332/omistories
    username: user
    password: password


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_second_level_cache: false  # Disabilita la cache di secondo livello
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
